config/routes.rb
Rails.application.routes.draw do
  root :to => 'bonus_codes#index'

  get 'bonus_codes/validate' => 'bonus_codes#validate', :as => :validate_bonus
end

app/models/bonus.rb
class Bonus < ActiveRecord::Base
  belongs_to :product

  scope :by_code, ->(value) { where(:code => value) }
  scope :sold, -> { where(:sold => true) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :bonuses, :class_name => 'Bonus'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bonus_codes_controller.rb
class BonusCodesController < ApplicationController
  def index
    @products = Product.all
  end

  def validate
    product = Product.find(params[:product_id])
    result = BonusGuard.validate(product, params[:bonus_code])
    case result
    when :valid
      head 200
    when :invalid
      head 403
    else
      head 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bonus_codes/index.html.erb
<div data-alert="true" id="bonus-valid" class="alert alert-success">Bonus is valid</div>
<div data-alert="true" id="bonus-not-sold" class="alert alert-warning">Bonus is not sold</div>
<div data-alert="true" id="bonus-not-found" class="alert alert-danger">Bonus is not found</div>

<h3>Check Your Product Bonus</h3>

<%= form_tag validate_bonus_path, method: :get, role: :form, class: 'form-inline', id: 'check-form', remote: true do %>
  <div class="form-group">
    <%= select_tag :product_id, options_from_collection_for_select(@products, :id, :name),
      prompt: "Select Product", class: 'form-control' %>
    <%= text_field_tag :bonus_code, '', placeholder: 'Enter Bonus Code', class: 'form-control' %>
    <%= submit_tag 'Validate', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puncher</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="jumbotron">
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>